baseurl = "https://berndpfrommer.github.io/tagslam_web/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "TagSLAM"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

#pygmentsUseClasses = true
#pygmentsCodefences = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = false

[Params]
    # Souce Code repository section
    # description = "Tag-based SLAM!"
    github_repository = "https://github.com/berndpfrommer/tagslam_root"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/berndpfrommer/tagslam_web"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification

    # Theme settings section

    # path name excluded from documentation menu

    custom_font_color = ""
    custom_background_color = ""

    menu_style = "open-menu"
    dateformat = "" # default "2 Jan 2006"
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
#    defaultMarkdownHandler = "blackfriday"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS"]
